config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :products do
      resources :product_files do
        collection do
          post :update_positions
        end
      end
    end
  end
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :products do
        resources :product_files
      end
    end
  end
end

app/models/spree/product_decorator.rb
module Spree::ProductDecorator
  def self.prepended(base)
    base.has_many :product_files, -> { order(:position) }, as: :viewable, dependent: :destroy
  end
end

::Spree::Product.prepend ::Spree::ProductDecorator

app/models/spree/product_file.rb
class Spree::ProductFile < Spree::Asset
  validate :check_attachment_presence

  has_one_attached :attachment

  def check_attachment_presence
    unless attachment.attached?
      attachment.purge
      errors.add(:attachment, :attachment_must_be_present)
    end
  end

  include Rails.application.routes.url_helpers

  def display_name
    alt.blank? ? attachment.filename : alt
  end

end

app/controllers/spree/admin/product_files_controller.rb
module Spree
  module Admin
    class ProductFilesController < ResourceController
      before_action :load_edit_data, except: :index
      before_action :load_index_data, only: :index

      create.before :set_viewable
      update.before :set_viewable
      create.fails :set_flash_error_messages_from_object

      private

      def location_after_destroy
        admin_product_product_files_url(@product)
      end

      def location_after_save
        admin_product_product_files_url(@product)
      end

      def load_index_data
        @product = Product.friendly.find(params[:product_id])
      end

      def load_edit_data
        @product = Product.friendly.find(params[:product_id])
      end

      def set_viewable
        @product_file.viewable_type = 'Spree::Product'
        @product_file.viewable_id = @product.id
      end

      def variant_index_includes
        [
          variant_product_files: [viewable: { option_values: :option_type }]
        ]
      end

      def variant_edit_includes
        [
          variants_including_master: { option_values: :option_type, product_files: :viewable }
        ]
      end

      def set_flash_error_messages_from_object
        flash[:error] = @object.errors.full_messages.join(', ')
      end

    end
  end
end

app/controllers/spree/api/v1/product_files_controller.rb
module Spree
  module Api
    module V1
      class ProductFilesController < Spree::Api::V2::BaseController

        include ::SpreeApiV1ProductFilesHelper

        def index
          @product_files = scope.product_files.accessible_by(current_ability, :read)
          respond_with(@product_files)
        end

        def show
          @product_file = ProductFile.accessible_by(current_ability, :read).find(params[:id])
          respond_with(@product_file)
        end

        def new; end

        def create
          authorize! :create, ProductFile
          @product_file = scope.product_files.new(product_file_params)
          if @product_file.save
            respond_with(@product_file, status: 201, default_template: :show)
          else
            invalid_resource!(@product_file)
          end
        end

        def update
          @product_file = scope.product_files.accessible_by(current_ability, :update).find(params[:id])
          if @product_file.update(product_file_params)
            respond_with(@product_file, default_template: :show)
          else
            invalid_resource!(@product_file)
          end
        end

        def destroy
          @product_file = scope.product_files.accessible_by(current_ability, :destroy).find(params[:id])
          @product_file.destroy
          respond_with(@product_file, status: 204)
        end

        private

        def permitted_product_file_attributes
          [:alt, :attachment, :position, :viewable_type, :viewable_id]
        end

        def product_file_params
          params.require(:product_file).permit(permitted_product_file_attributes)
        end

        def scope
          if params[:product_id]
            Spree::Product.friendly.find(params[:product_id])
          elsif params[:variant_id]
            Spree::Variant.find(params[:variant_id])
          end
        end
      end
    end
  end
end

app/helpers/spree_api_v1_product_files_helper.rb
module SpreeApiV1ProductFilesHelper

  @@product_file_attributes = [
    :id, :position, :attachment_content_type, :attachment_file_name, :type, :attachment_updated_at, :alt
  ]

  def product_file_attributes
    @@product_file_attributes
  end

end

app/views/spree/admin/product_files/_form.html.erb
<div data-hook="admin_image_form_fields" class="row">
  <div data-hook="alt_text" class="col-md-6">
    <div class="form-group">
      <%= f.label :alt, Spree.t(:name) %>
      <%= f.text_field :alt, class: 'form-control title' %>
    </div>
  </div>
  <div class="col-md-6">
    <div data-hook="file" class="form-group">
      <%= f.label :attachment, Spree.t(:filename) %>
      <%= f.file_field :attachment %>
    </div>
  </div>
</div>

app/views/spree/admin/product_files/edit.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :product_files } %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @product_file } %>

<%= form_for [:admin, @product, @product_file], html: { multipart: true } do |f| %>
  <div data-hook="edit_product_file" class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">
        <%= @product_file.attachment_file_name %>
      </h1>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <div class="col-md-3 text-center">
          <%= link_to @product_file.attachment.filename, main_app.rails_blob_path(@product_file.attachment, disposition: "attachment") %>

        </div>
        <div class="col-md-9">
          <%= render partial: 'form', locals: { f: f } %>
        </div>

        <div class="form-actions" data-hook="buttons">
          <%= button Spree.t('actions.update'), 'save' %>
          <span class="or"><%= Spree.t(:or) %></span>
          <%= button_link_to Spree.t('actions.cancel'), spree.admin_product_product_files_url(@product), id: 'cancel_link', icon: 'delete' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/spree/admin/product_files/index.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :product_files } %>

<% content_for :page_actions do %>
  <%= button_link_to(Spree.t(:new_product_file), spree.new_admin_product_product_file_url(@product), { class: "btn-success", icon: 'add', id: 'new_product_file_link' }) if can? :create, Spree::ProductFile %>
<% end %>

<% if @product.product_files.empty? %>
  <div class="alert alert-warning no-objects-found">
    <%= Spree.t(:no_product_files) %>
  </div>
<% else %>

  <table class="table sortable" data-hook="product_files_table" data-sortable-link="<%= update_positions_admin_product_product_files_url(@product) %>">
    <thead>
      <tr data-hook="product_files_header">
        <th colspan="2">
          <%= Spree.t(:product_file) %>
        </th>
        <th>
          <%= Spree.t(:name) %>
        </th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% @product.product_files.each do |product_file| %>
        <tr id="<%= spree_dom_id product_file %>" data-hook="product_files_row">
          <td class="move-handle text-center">
            <% if can? :edit, product_file %>
              <span class="icon icon-move handle"></span>
            <% end %>
          </td>
          <td class="product_file">
            <%= link_to product_file.attachment.filename, main_app.rails_blob_path(product_file.attachment, disposition: "attachment") %>
          </td>
          <td><%= product_file.alt %></td>
          <td class="actions actions-2 text-right">
            <%= link_to_with_icon('edit', Spree.t(:edit), spree.edit_admin_product_product_file_url(@product, product_file), class: 'btn btn-primary btn-sm', no_text: true, data: { action: 'edit' }) if can? :edit, product_file %>
            <%= link_to_delete(product_file, { url: spree.admin_product_product_file_url(@product, product_file), no_text: true }) if can? :destroy, product_file %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

app/views/spree/admin/product_files/new.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :product_files } %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @product } %>

<% content_for :page_title do %>
  <%= Spree.t(:new_product_file) %>
<% end %>

<%= form_for [:admin, @product, @product_file], html: { multipart: true } do |f| %>
  <fieldset data-hook="new_image">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.create'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_product_product_files_url(@product), icon: 'delete', id: 'cancel_link' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/products/_product_files.html.erb
<li<%== ' class="active"' if current == :product_files %>>
  <%= link_to_with_icon 'file', Spree.t(:product_files), admin_product_product_files_url(@product), class: "nav-link" %>
</li>

app/views/spree/products/_product_files.html.erb
<ul class="product_files">
  <% @product.product_files.each do |product_file| %>
    <li>
      <%= link_to product_file.display_name, main_app.rails_blob_path(product_file.attachment, disposition: "attachment") %>
    </li>
  <% end %>
</ul>